language: node_js

node_js:
 - "0.10"
 - "0.11"
 - "0.12"
 - "iojs-v1.0"
 - "iojs-v1.1"
 - "iojs-v1.2"
 - "iojs-v1.3"
 - "iojs-v1.4"
 - "iojs-v1.5"
 - "iojs-v1.6"
 - "iojs-v1.7"
 - "iojs-v1.8"
 - "iojs-v2.0"
